version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todoapp
      - NODE_ENV=production
    depends_on:
      mongo:
        condition: service_healthy
    restart: always # Ensures the backend restarts if it crashes
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started
    restart: always # Ensures the frontend restarts if it crashes
    volumes:
      - ./frontend:/app
      - /app/node_modules

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always # Ensures MongoDB restarts if it crashes

volumes:
  mongo-data:
    driver: local
